development:
  cloud_name: dehhkgwah
  api_key: '435511164522373'
  api_secret: uAh7WJC6IIk8sN0XOaDwQ5I1-WA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dehhkgwah
  api_key: '435511164522373'
  api_secret: uAh7WJC6IIk8sN0XOaDwQ5I1-WA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dehhkgwah
  api_key: '435511164522373'
  api_secret: uAh7WJC6IIk8sN0XOaDwQ5I1-WA
  enhance_image_tag: true
  static_image_support: false
